### PR TITLE
Adding possible improvements

### LINKED ISSUE #132: Perf improvements and cleanups
Hello,

I was reading the code so I saw opportunities for some simple improvements/cleanups...

- I removed unused imports and variables;
- I changed some `else` unnecessaries;
- I changed some `let` variables to `const` because they are not rewritten.

**Feels comfortable to discard any change I made...**

> _Happy Christmas_

### PR DESCRIPTION
**Pull request by ftonato**
**Summary**

This PR fixes the following **bugs/features**

* [ ] #132 

**Closing issues**
Fixes #132

### CODE REVIEW

**Comment by DanielJDufour** [comment]
Thanks @ftonato and happy holidays! :-)

**Comment by ftonato** [comment]
Hello @DanielJDufour,

Please, consider check [my tests](https://repl.it/@ftonato/getReposCount-GSAcode-gov-front-end) about the commit [27e551e](https://github.com/GSA/code-gov-front-end/pull/133/commits/27e551eb800f8c91b5814eced5de09499fa8bd9e).

**Comment by ftonato** [comment]
Hello @DanielJDufour,

Please, consider check [my tests](https://repl.it/@ftonato/getReposCount-GSAcode-gov-front-end) about the commit [27e551e](https://github.com/GSA/code-gov-front-end/pull/133/commits/27e551eb800f8c91b5814eced5de09499fa8bd9e).

**Comment by ftonato** [comment]
Hello @DanielJDufour,

Please, consider check [my tests](https://repl.it/@ftonato/getReposCount-GSAcode-gov-front-end) about the commit [55c00f4](https://github.com/GSA/code-gov-front-end/pull/133/commits/55c00f4218829385185edbaf00092cd3bc9c60f6).

**Comment by ftonato** [comment]
Just one comment about my last commit - https://www.npmjs.com/package/react-html-parser

**Comment by saracope** [comment]
Thanks for the PR's @ftonato! We are back in the office starting today (after the gov shutdown) and will look at this in the coming week.

**Comment by saracope** [comment]
Thanks for the PR @ftonato. When I pull this down locally, the app does not load and throws several console errors.  Looks to be related to the variable changes. Can you please review?

**Comment by ftonato** [comment]
Hello @saracope,

I fixed my mistakes, but as you know there are so many `console.whatever` on _our_ code =(

**Comment by saracope** [comment]
@ftonato I'm still getting errors locally on this one. The Browse Projects and Open Tasks pages aren't loading at all. Can you take a look?

**Comment by ftonato** [comment]
Hello @saracope,

I'm sorry, I really forgot to answer this issue.
I will reserve some time today to look at this and give will feedback.

**Comment by ftonato** [comment]
Hi @saracope,

I updated, you can re-check, please.

_I don't fixed the conflicts because you can do it using GitHub itself, anyway I can do it too..._

**Comment by saracope** [comment]
Thanks. Please go ahead and resolve the conflicts.

**Comment by ftonato** [comment]
**Important note**

We should make the merge as quickly as possible.

The longer we take, the harder it will be to keep this pull-request problem-free ...

**Comment by ftonato** [comment]
`OmG` :fearful:, I'm sorry =(

I will remove my last commit and please, do the merge to fix based on our project preferences (last updates).

**Comment by ftonato** [comment]
Hello @saracope,
Let me know when this will be updated, please!

**Comment by saracope** [comment]
Resolved the conflicts so this is updated with the current Master branch:
https://github.com/GSA/code-gov-front-end/compare/ftonato-feature-improvements?expand=1

**Comment by ftonato** [comment]
@saracope Check this out - https://github.com/GSA/code-gov-front-end/issues/132#issuecomment-504377062

**Pull request merged**
