### PR TITLE
remove Labor Hours

### PR DESCRIPTION
**Pull request by afomi**
https://github.com/GSA/code-gov-front-end/issues/351

Note: this includes some formatting changes enforced by `package.json`, that run on commit.

### CODE REVIEW

**Comment by afomi** [comment]
Tests are failing on some mismatched DOM element identifiers. Not exactly sure what's going on here yet. Will need to dig deeper.

**Comment by afomi** [comment]
tests pass in circle 

🤷‍♂️ and 👍

**Comment by jcastle** [comment]
@afomi, thanks again for submitting this PR! We are going to leave this one here for a bit. We plan to kick off a Code.gov Schema 2.0 update project this summer. We plan to update the schema, front-end, API, and need to give agencies time to update their json files. What you have done here definitely helps us for considering how to update the entire file in the future.

**Comment by jcastle** [comment]
@afomi, going to close this one for now. We plan to update the schema at some point but not on the short-term radar as originally thought. If/when this topic is addressed, I will reopen this PR as a starting point. Thank you for all your submissions to our platform.

**Pull request closed without merging**
