### PR TITLE
Updated nvm text from 10.15.1 to 10.19.0

### PR DESCRIPTION
**Pull request by jcastle**
This is an addition to PR #174

### CODE REVIEW

**Comment by hursey013** [comment]
Looks good, not sure what happened with Federalist but I'm guessing kicking off a new build will solve the issue.

**Comment by jcastle** [comment]
@hursey013, I don't see this in the Federalist builds to rebuild. I kept clicking on the build you had for implementing 10.19. Can you help kick off another build or point me in the right direction?

**Comment by hursey013** [comment]
@jcastle the easiest way I've found to restart builds is to just force push the branch again which restarts all of the tests/builds. I just tried it so we'll see if it fixes the Federalist build.

**Comment by jcastle** [comment]
Too funny! Two character change in the README file.

**Pull request merged**
