### PR TITLE
Adding possible improvements w/ fix merge

### LINKED ISSUE #132: Perf improvements and cleanups
Hello,

I was reading the code so I saw opportunities for some simple improvements/cleanups...

- I removed unused imports and variables;
- I changed some `else` unnecessaries;
- I changed some `let` variables to `const` because they are not rewritten.

**Feels comfortable to discard any change I made...**

> _Happy Christmas_

### PR DESCRIPTION
**Pull request by ftonato**
**Summary**

This PR fixes the following **bugs/features**

* [ ] #132 

**Closing issues**
Fixes #132

### CODE REVIEW

**Comment by ftonato** [comment]
@saracope Check this out - https://github.com/GSA/code-gov-front-end/issues/132#issuecomment-504377062

**Comment by saracope** [comment]
@ftonato Can you merge in Master to get these checks to refire?

**Comment by ftonato** [comment]
@saracope I don't understood your request :confused:

Are you suggesting to me create a new pull-request with my last commit to branch master?

----

The branch `ftonato-feature-improvements` already is up-to-date with the master, like you can see below:

up-to-date

**Comment by saracope** [comment]
No. I'm saying that you need to merge in the latest update from Master. That should fix your failing Code Climate check.

**Comment by ftonato** [comment]
Hello @saracope,

I have created two different pull-requests;

First of them: #257 is a simple piece of code used to distribute responsibilities between methods that will help to improve the cognitive complexity and the last one #258 is your requested merge between *master* and *ftonato-feature-improvements*.

You can accept both in the order in which they were created.

**Comment by saracope** [comment]
@ftonato CodeClimate is still failing here

**Comment by ftonato** [comment]
@saracope  I'll check it out today and write you anything about it as soon as possible.

**Comment by ftonato** [comment]
@saracope You need to merge #260 issue and you'll finally be available to merge this PR :)

**Comment by ftonato** [comment]
hey @saracope, can you check the PR #260 to solve the above cognitive complexity problem?

**Pull request merged**
