### PR TITLE
Official banner

### PR DESCRIPTION
**Pull request by Michael-Hanley**
**Summary**

PR adds the option of adding the official banner used by code.ca.gov

image

Explain the **motivation** for making this change. What existing problem does the pull request solve?

We have added this as part of getting code.ca.gov up and running. There was requests for it to be added and we felt that other agencies could possibly use it. 

Feature can be turned on or off from the site.config file. 

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

turn on functionality in site config.
Run server.
official-banner should pop up on top of the menu.
route from page to page ensuring it is consistent.
scroll up and down to ensure it stays in it's correct location.
expand the search-box to ensure it is correctly revealed.
switch to mobile view.
Ensure mobile menu is working correctly.

Turn off feature and repeat actions to ensure it works with the feature being off.

### CODE REVIEW

**Comment by saracope** [comment]
Thank you for the contribution, @Michael-Hanley! This is a great addition and I like how you incorporated this banner into the site config. My gut is telling me to move the styles over to the style guide as a common component though. 🤔

I'm going to ask our designer to review to give feeback on the overall look & feel.

**Comment by Michael-Hanley** [comment]
Sounds great! Let me know if you'd like me to open a PR on the style guide and I'd be happy to do so.  

Thank you!

**Comment by saracope** [comment]
@Michael-Hanley Ok, here's what we've decided:
[ ] PR the adding and main styling of the banner in [code-gov-style](https://github.com/GSA/code-gov-style). Match this to the gov banner in [USWDS 2.0](https://v2.designsystem.digital.gov/components/headers/)
[ ] Do this as a new component gov_banner

For this PR on code-gov-front-end:
[ ] On the home page, the banner should be $color-gray-dark
[ ] On the sub-pages, the banner should be #F0F3F7

Happy to answer questions and can chat more if you want in our Slack also. Thanks!

**Comment by saracope** [comment]
Closing out as this was added in another PR.

**Pull request closed without merging**
